H5_DIR = "h5data/"
AUDIO_DIR = "audio/"
PLOTS_DIR = "plots/"
DATA_DIR = "data/"
INTERPRETABLE_NEURONS = DATA_DIR + "interpretable_neurons_per_trait.json"
BREF_MEDIAN_ACTIVATIONS = DATA_DIR + "median_activation_per_neuron_per_phoneme.json"
NUMERIC_PHONES = DATA_DIR + "numeric_phones.json"
PHONETIC_TRAIT_PHONES = DATA_DIR + "phonetic_traits.json"
DEAD_NEURONS = DATA_DIR + "dead_neurons.json"
NORMALIZATION_FACTORS = DATA_DIR + "normalization_factors.json"
PHONES_PER_NEURON = DATA_DIR + "phonemes_per_neuron.json"

TFRECORD_DIR = "tfrecords/"
PHONES_JSON = DATA_DIR + "numeric_phones.json"
